name: Auto Update Booking Status

on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes
  workflow_dispatch:

jobs:
  call-supabase-edge-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Content-Type: application/json" \
            https://dktxspcehngtrbnvhkfh.functions.supabase.co/auto_update_booking_status
